# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/Users/mac/Desktop/libosmscout/libosmscout/src/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/Users/mac/Desktop/libosmscout/libosmscout/./include"
package="libosmscout"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libosmscout"
;; --help) pkg-config --help ; echo Buildscript Of "libosmscout base library"
;; --modversion|--version) echo "0.1"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-losmscout -D_THREAD_SAFE -pthread -L/usr/local/Cellar/libmarisa/0.2.4_1/lib -lmarisa"
:
;; --cflags) echo -I${includedir} "-D_THREAD_SAFE -pthread -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -I/usr/local/Cellar/libmarisa/0.2.4_1/include"
:
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
