# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/Users/mac/Desktop/libosmscout/libosmscout-map-iOSX/src/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/Users/mac/Desktop/libosmscout/libosmscout-map-iOSX/./include"
package="libosmscout-map-iOSX"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libosmscout-map-iOSX"
;; --help) pkg-config --help ; echo Buildscript Of "libosmscout map rendering iOS/Mac OS X backend library"
;; --modversion|--version) echo "0.1"
;; --requires) echo pkg-config libosmscout libosmscout-map "libosmscout libosmscout-map"
;; --libs) echo -L${libdir} "" "-losmscoutmapiOSX -L/Users/mac/Desktop/libosmscout/libosmscout/src/.libs -L/usr/local/Cellar/libmarisa/0.2.4_1/lib -L/Users/mac/Desktop/libosmscout/libosmscout-map/src/.libs -losmscoutmap -losmscout -D_THREAD_SAFE -pthread -lmarisa"
pkg-config libosmscout libosmscout-map
;; --cflags) echo -I${includedir} ""
pkg-config libosmscout libosmscout-map
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
